// src/utils/kenyaData.js
export const KENYA_COUNTIES = [
  'Mombasa', 'Kwale', 'Kilifi', 'Tana River', 'Lamu', 'Taita Taveta',
  'Garissa', 'Wajir', 'Mandera', 'Marsabit', 'Isiolo', 'Meru', 'Tharaka Nithi',
  'Embu', 'Kitui', 'Machakos', 'Makueni', 'Nyandarua', 'Nyeri', 'Kirinyaga',
  'Muranga', 'Kiambu', 'Turkana', 'West Pokot', 'Samburu', 'Trans Nzoia',
  'Uasin Gishu', 'Elgeyo Marakwet', 'Nandi', 'Baringo', 'Laikipia', 'Nakuru',
  'Narok', 'Kajiado', 'Kericho', 'Bomet', 'Kakamega', 'Vihiga', 'Bungoma',
  'Busia', 'Siaya', 'Kisumu', 'Homa Bay', 'Migori', 'Kisii', 'Nyamira', 'Nairobi'
];

export // Cities/Towns by County
const COUNTY_CITIES = {
  'Mombasa': ['Mombasa CBD', 'Nyali', 'Bamburi', 'Likoni', 'Kilindini', 'Mtwapa'],
  'Kwale': ['Ukunda', 'Diani Beach', 'Msambweni', 'Kinango', 'Lunga Lunga'],
  'Kilifi': ['Kilifi Town', 'Malindi', 'Watamu', 'Mtwapa', 'Mariakani'],
  'Tana River': ['Hola', 'Garsen', 'Madogo', 'Bura'],
  'Lamu': ['Lamu Town', 'Shella', 'Mpeketoni', 'Faza'],
  'Taita Taveta': ['Voi', 'Wundanyi', 'Taveta', 'Mwatate'],
  'Garissa': ['Garissa Town', 'Dadaab', 'Balambala', 'Masalani'],
  'Wajir': ['Wajir Town', 'Habasswein', 'Eldas', 'Griffu'],
  'Mandera': ['Mandera Town', 'Elwak', 'Rhamu', 'Takaba'],
  'Marsabit': ['Marsabit Town', 'Moyale', 'Loiyangalani', 'North Horr'],
  'Isiolo': ['Isiolo Town', 'Garbatulla', 'Merti', 'Kinna'],
  'Meru': ['Meru Town', 'Maua', 'Chuka', 'Nkubu', 'Timau'],
  'Tharaka Nithi': ['Chuka', 'Kathwana', 'Marimanti', 'Mitheru'],
  'Embu': ['Embu Town', 'Runyenjes', 'Siakago', 'Manyatta'],
  'Kitui': ['Kitui Town', 'Mwingi', 'Mutomo', 'Kyuso'],
  'Machakos': ['Machakos Town', 'Kangundo', 'Tala', 'Mavoko', 'Athi River'],
  'Makueni': ['Wote', 'Kibwezi', 'Makindu', 'Sultan Hamud'],
  'Nyandarua': ['Ol Kalou', 'Nyahururu', 'Engineer', 'Kinamba'],
  'Nyeri': ['Nyeri Town', 'Karatina', 'Othaya', 'Mukurweini', 'Naro Moru'],
  'Kirinyaga': ['Kerugoya', 'Kutus', 'Kianyaga', 'Baricho'],
  'Muranga': ['Muranga Town', 'Kangema', 'Kigumo', 'Kenol'],
  'Kiambu': ['Kiambu Town', 'Thika', 'Limuru', 'Ruiru', 'Kikuyu', 'Juja'],
  'Turkana': ['Lodwar', 'Lokichoggio', 'Kakuma', 'Lokitaung'],
  'West Pokot': ['Kapenguria', 'Chepareria', 'Kacheliba', 'Kodich'],
  'Samburu': ['Maralal', 'Baragoi', 'Archers Post', 'Wamba'],
  'Trans Nzoia': ['Kitale', 'Kiminini', 'Endebess', 'Saboti'],
  'Uasin Gishu': ['Eldoret', 'Kapsabet', 'Moiben', 'Turbo'],
  'Elgeyo Marakwet': ['Iten', 'Kapsowar', 'Tambach', 'Chesoi'],
  'Nandi': ['Kapsabet', 'Nandi Hills', 'Mosoriot', 'Kabiyet'],
  'Baringo': ['Kabarnet', 'Eldama Ravine', 'Marigat', 'Mogotio'],
  'Laikipia': ['Nanyuki', 'Nyahururu', 'Rumuruti', 'Kinamba', 'Ngarua'],
  'Nakuru': ['Nakuru Town', 'Naivasha', 'Gilgil', 'Molo', 'Njoro', 'Rongai'],
  'Narok': ['Narok Town', 'Kilgoris', 'Mai Mahiu', 'Ololulunga'],
  'Kajiado': ['Kajiado Town', 'Ngong', 'Kitengela', 'Loitokitok', 'Ongata Rongai'],
  'Kericho': ['Kericho Town', 'Litein', 'Bomet', 'Sotik', 'Kipkelion'],
  'Bomet': ['Bomet Town', 'Sotik', 'Chepalungu', 'Konoin'],
  'Kakamega': ['Kakamega Town', 'Mumias', 'Butere', 'Lugari', 'Malava'],
  'Vihiga': ['Vihiga Town', 'Mbale', 'Luanda', 'Sabatia'],
  'Bungoma': ['Bungoma Town', 'Kimilili', 'Webuye', 'Chwele'],
  'Busia': ['Busia Town', 'Malaba', 'Nambale', 'Bumala'],
  'Siaya': ['Siaya Town', 'Bondo', 'Yala', 'Ugunja'],
  'Kisumu': ['Kisumu City', 'Ahero', 'Kombewa', 'Muhoroni', 'Maseno'],
  'Homa Bay': ['Homa Bay Town', 'Mbita', 'Oyugis', 'Rodi Kopany'],
  'Migori': ['Migori Town', 'Kehancha', 'Rongo', 'Awendo'],
  'Kisii': ['Kisii Town', 'Nyamira', 'Keroka', 'Ogembo', 'Suneka'],
  'Nyamira': ['Nyamira Town', 'Keroka', 'Manga', 'Borabu'],
  'Nairobi': ['Nairobi CBD', 'Westlands', 'Karen', 'Langata', 'Kilimani', 'Parklands', 'Eastlands', 'South B', 'South C', 'Embakasi', 'Kasarani', 'Roysambu']
};